# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20170314_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='total_exp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calculator',
            name='total_inc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
