# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 16:05
from __future__ import unicode_literals

import calculator.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20170405_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='total_exp',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='total_inc',
        ),
        migrations.AlterField(
            model_name='budgetexpenses',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[calculator.validators.more_than_zero_validator]),
        ),
        migrations.AlterField(
            model_name='budgetincome',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[calculator.validators.more_than_zero_validator]),
        ),
    ]
